let lessons=[
    {
        subject:"Math",
        location:"London",
        price:55,
        space:5,
        imageURL:"images/math.png"
    },
    {
        subject:"Programming",
        location:"Manchester",
        price:67,
        space:5,
        imageURL:"images/programming.png"
    },
    {
        subject:"Geography",
        location:"Greenwich",
        price:75,
        space:5,
        imageURL:"images/geography.png"
    },
    {
        subject:"Biology",
        location:"Belfast",
        price:98,
        space:5,
        imageURL:"images/biology.png"
    },{
        subject:"Swimming",
        location:"London",
        price:58,
        space:5,
        imageURL:"images/swimming.png"
    },
    {
        subject:"Dancing",
        location:"Manchester",
        price:115,
        space:5,
        imageURL:"images/dancing.png"
    },
    {
        subject:"Singing",
        location:"Greenwich",
        price:140,
        space:5,
        imageURL:"images/singing.png"
    },
    {
        subject:"English",
        location:"Berkshire",
        price:136,
        space:5,
        imageURL:"images/english.png"
    },{
        subject:"Spanish",
        location:"Birmingham",
        price:125,
        space:5,
        imageURL:"images/spanish.png"
    },
    {
        subject:"German",
        location:"Cambridge",
        price:131,
        space:5,
        imageURL:"images/german.png"
    },

]